export const ADMINISTRADOR_GLOBAL = 'ADMINISTRADOR_GLOBAL';
export const ADMINISTRADOR = 'ADMINISTRADOR';
export const RECEPCAO = 'RECEPCAO';
export const FINANCEIRO = 'FINANCEIRO';
export const MEDICO = 'MEDICO';
